spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.host:db}:${db.port:3306}/${db.schema}?useUnicode=true&characterEncoding=utf8&useSSL=false&statementInterceptors=brave.mysql.TracingStatementInterceptor
    username: ${db.username:root}
    password: ${db.password:root}

jrpc:
  server:
    name: ${spring.application.name}
    version: 1.0
    port: 3001
  trace:
    more: true
j-jdbc:
  tableInit: 3

